export type BudgetCategory = { label: string; suggested: number };

export type SprintTemplate = {
  id: string;
  name: string;
  emoji: string;
  category: string;
  title: string;
  description: string;
  durationDays: number;
  milestones: string[];
  budgetCategories?: BudgetCategory[];
};

export const SPRINT_TEMPLATES: SprintTemplate[] = [
  {
    id: "12-week-progress",
    name: "12 Week Progress Sprint",
    emoji: "🚀",
    category: "Productivity",
    title: "12 Week Progress Sprint",
    description: "Compress a year of progress into 12 focused weeks toward one big goal.",
    durationDays: 84,
    milestones: [
      "Week 1 — Define the one goal & success metric",
      "Week 2 — Break goal into weekly outcomes",
      "Week 3 — Build the daily habit stack",
      "Week 4 — First measurable result",
      "Week 5 — Review & remove what isn't working",
      "Week 6 — Midpoint check-in: are we on pace?",
      "Week 7 — Double down on what's working",
      "Week 8 — Push past the dip",
      "Week 9 — Stretch goal attempt",
      "Week 10 — Polish & refine",
      "Week 11 — Final push week",
      "Week 12 — Ship, celebrate, retrospective",
    ],
  },
  {
    id: "vacation-savings",
    name: "Vacation Savings Goal",
    emoji: "🏖️",
    category: "Finance",
    title: "Save for my dream vacation",
    description: "A step-by-step savings sprint to fund your next trip without the stress.",
    durationDays: 180,
    milestones: [
      "Pick destination & set total budget",
      "Open a dedicated savings account",
      "Set up automatic weekly transfer",
      "Hit 10% of savings goal",
      "Cut one recurring expense & redirect it",
      "Hit 25% of savings goal",
      "Book flights during a sale",
      "Hit 50% of savings goal",
      "Reserve accommodation",
      "Hit 75% of savings goal",
      "Plan daily itinerary & buffer for extras",
      "Hit 100% — pack and go!",
    ],
  },
  {
    id: "college-prep",
    name: "High School → College Prep",
    emoji: "🎓",
    category: "Education",
    title: "College application prep sprint",
    description: "From test prep to submitted applications — a clear path to your dream school.",
    durationDays: 270,
    milestones: [
      "Build target college list (reach / match / safety)",
      "Register for SAT or ACT",
      "Complete first full practice test",
      "Take official SAT/ACT",
      "Draft personal statement",
      "Request letters of recommendation",
      "Finalize résumé of activities & awards",
      "Polish & finalize main essay",
      "Complete supplemental essays",
      "Submit FAFSA / financial aid forms",
      "Submit early action / early decision apps",
      "Submit regular decision apps",
    ],
  },
  {
    id: "fitness-90",
    name: "90-Day Fitness Transformation",
    emoji: "💪",
    category: "Health",
    title: "90-Day Fitness Sprint",
    description: "Build a sustainable training & nutrition routine over 90 days.",
    durationDays: 90,
    milestones: [
      "Take baseline measurements & photos",
      "Pick a training plan & schedule sessions",
      "Complete week 1 of workouts",
      "Lock in nutrition basics (protein + water)",
      "Hit 10 workouts completed",
      "30-day check-in: photos & measurements",
      "Increase intensity or volume",
      "Hit 25 workouts completed",
      "60-day check-in",
      "Add mobility / recovery routine",
      "Final week — peak effort",
      "Take final measurements & celebrate",
    ],
  },
  {
    id: "side-project-launch",
    name: "Side Project Launch",
    emoji: "🛠️",
    category: "Build",
    title: "Launch my side project",
    description: "From idea to first paying users in a focused build sprint.",
    durationDays: 60,
    milestones: [
      "Write one-paragraph project pitch",
      "Talk to 5 potential users",
      "Build MVP scope (cut everything else)",
      "Ship landing page",
      "Build core feature v1",
      "Invite 10 beta users",
      "Collect feedback & iterate",
      "Set pricing",
      "Public launch post",
      "First paying customer",
      "Reach 10 paying customers",
      "Retrospective & decide what's next",
    ],
  },
  {
    id: "learn-skill",
    name: "Learn a New Skill",
    emoji: "📚",
    category: "Learning",
    title: "Learn a new skill",
    description: "Go from zero to confident in any skill with structured weekly progress.",
    durationDays: 60,
    milestones: [
      "Pick the skill & define 'done'",
      "Choose primary learning resource",
      "Schedule weekly practice blocks",
      "Complete fundamentals module",
      "First small project / exercise",
      "Find a community or accountability partner",
      "Intermediate concepts complete",
      "Build a portfolio-worthy project",
      "Teach the concept to someone else",
      "Get feedback from a more advanced practitioner",
      "Capstone project",
      "Share what you built publicly",
    ],
  },
];
