/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as StepsRouteImport } from './routes/steps'
import { Route as HowRouteImport } from './routes/how'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWinsRouteImport } from './routes/_authenticated/wins'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAffirmationsRouteImport } from './routes/_authenticated/affirmations'
import { Route as AuthenticatedSprintsIndexRouteImport } from './routes/_authenticated/sprints.index'
import { Route as AuthenticatedSprintsIdRouteImport } from './routes/_authenticated/sprints.$id'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const StepsRoute = StepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWinsRoute = AuthenticatedWinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffirmationsRoute =
  AuthenticatedAffirmationsRouteImport.update({
    id: '/affirmations',
    path: '/affirmations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprintsIndexRoute =
  AuthenticatedSprintsIndexRouteImport.update({
    id: '/sprints/',
    path: '/sprints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprintsIdRoute = AuthenticatedSprintsIdRouteImport.update({
  id: '/sprints/$id',
  path: '/sprints/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/steps': typeof StepsRoute
  '/why': typeof WhyRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/sprints/$id': typeof AuthenticatedSprintsIdRoute
  '/sprints/': typeof AuthenticatedSprintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/steps': typeof StepsRoute
  '/why': typeof WhyRoute
  '/affirmations': typeof AuthenticatedAffirmationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/wins': typeof AuthenticatedWinsRoute
  '/sprints/$id': typeof AuthenticatedSprintsIdRoute
  '/sprints': typeof AuthenticatedSprintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/how': typeof HowRoute
  '/steps': typeof StepsRoute
  '/why': typeof WhyRoute
  '/_authenticated/affirmations': typeof AuthenticatedAffirmationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/wins': typeof AuthenticatedWinsRoute
  '/_authenticated/sprints/$id': typeof AuthenticatedSprintsIdRoute
  '/_authenticated/sprints/': typeof AuthenticatedSprintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/how'
    | '/steps'
    | '/why'
    | '/affirmations'
    | '/dashboard'
    | '/rewards'
    | '/wins'
    | '/sprints/$id'
    | '/sprints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how'
    | '/steps'
    | '/why'
    | '/affirmations'
    | '/dashboard'
    | '/rewards'
    | '/wins'
    | '/sprints/$id'
    | '/sprints'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/how'
    | '/steps'
    | '/why'
    | '/_authenticated/affirmations'
    | '/_authenticated/dashboard'
    | '/_authenticated/rewards'
    | '/_authenticated/wins'
    | '/_authenticated/sprints/$id'
    | '/_authenticated/sprints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowRoute: typeof HowRoute
  StepsRoute: typeof StepsRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wins': {
      id: '/_authenticated/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof AuthenticatedWinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affirmations': {
      id: '/_authenticated/affirmations'
      path: '/affirmations'
      fullPath: '/affirmations'
      preLoaderRoute: typeof AuthenticatedAffirmationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprints/': {
      id: '/_authenticated/sprints/'
      path: '/sprints'
      fullPath: '/sprints/'
      preLoaderRoute: typeof AuthenticatedSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprints/$id': {
      id: '/_authenticated/sprints/$id'
      path: '/sprints/$id'
      fullPath: '/sprints/$id'
      preLoaderRoute: typeof AuthenticatedSprintsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAffirmationsRoute: typeof AuthenticatedAffirmationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedWinsRoute: typeof AuthenticatedWinsRoute
  AuthenticatedSprintsIdRoute: typeof AuthenticatedSprintsIdRoute
  AuthenticatedSprintsIndexRoute: typeof AuthenticatedSprintsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAffirmationsRoute: AuthenticatedAffirmationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedWinsRoute: AuthenticatedWinsRoute,
  AuthenticatedSprintsIdRoute: AuthenticatedSprintsIdRoute,
  AuthenticatedSprintsIndexRoute: AuthenticatedSprintsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HowRoute: HowRoute,
  StepsRoute: StepsRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
